# Config file for conda package
#
#  To build, install & remove the development version:
#    git clone git+https://github.com/leftfield-geospatial/map-thicket-agc.git
#    conda build .
#    conda install -c conda-forge --use-local map-thicket-agc
#    conda remove -c conda-forge --use-local map-thicket-agc

package:
  name: map-thicket-agc
  version: 0.1.0

source:
  git_url: https://github.com/leftfield-geospatial/map-thicket-agc.git

requirements:
  run:
    - python >=3.6
    - geopandas >=0.8
    - rasterio >=1.1
    - numpy >=1.19
    - scipy >=1.5
    - scikit-learn >=0.23
    - matplotlib >=3.3
    - openpyxl >=3.0
    - dcor >=0.5


build:
  number: 0
  noarch: python
  script: pip install -e .

about:
  home: https://github.com/leftfield-geospatial/map-thicket-agc
  license: AGPLv3
